package com.choistec.cmspc.core.dto

const val ADMIN = "admin"
const val REARER = "rearer"
const val BABY = "baby"
const val _USER = "_user"
const val MEDICAL_DEPARTMENT = "medical_department"

const val COLUMNS = "COLUMNS"

const val ID = "id"
const val MAC = "mac"
const val DID = "did"
const val DEVICE = "device"
const val _ID = "_id"
const val NAME = "name"
const val PASSWORD = "password"
const val EMAIL = "email"
const val SEX = "sex"
const val BIRTHDAY = "birthday"
const val CONTACT = "contact"
const val DEL = "del_yn"
const val DATA = "data"
const val BATTERY = "battery"
const val REG_DATE = "reg_date"
const val MOD_DATE = "mod_date"
const val SEARCH_DATE = "search_date"
const val NOW = "utc_timestamp()"

const val ADMIN_ID = "$ADMIN$_ID"
const val REARER_ID = "$REARER$_ID"
const val DEVICE_ID = "$DEVICE$_ID"
const val BABY_ID = "$BABY$_ID"
const val MEDICAL_DEPARTMENT_ID = "$MEDICAL_DEPARTMENT$_ID"
const val HOSTPITAL_ID = "hostpital_id"

const val TEMP = "temp"
const val HEART = "heart"
const val BREATH = "breath"
const val SPO2 = "spo2"
const val WEIGHT = "weight"

const val DUST = "dust"
const val CO2 = "co2"
const val HUMI = "humi"
